INSERT INTO tag VALUES ('FAMILY') ON CONFLICT DO NOTHING;
INSERT INTO tag VALUES ('FOOD') ON CONFLICT DO NOTHING;
INSERT INTO tag VALUES ('WINE') ON CONFLICT DO NOTHING;
INSERT INTO tag VALUES ('WEEKEND') ON CONFLICT DO NOTHING;
